apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: github-tekon-quay-spring-14
  janus-idp.io/tekton: github-tekon-quay-spring-14
  backstage.io/kubernetes-id: github-tekon-quay-spring-14
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: github-tekon-quay-spring-14
resources:
- deployment.yaml
- route.yaml
- service.yaml
