apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tekon-quay-spring-14
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-jsmid:3ec13941d9f0bb658fa2f7f3394b08b4ca498d75@sha256:ffa625495e4e808f0d492f44e8c3888748ef9c9013d89ea59e812148102b2c9f
          name: container-image
